config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  unauthenticated do
    root 'site#index'
  end

  authenticated :user do
    resources :users, only: [:show, :edit, :update]
    resources :devices

    authenticated :user, ->(u) { u.is_client? } do
      root 'users#show'
    end

    authenticated :user, ->(u) { u.is_admin? } do
      root to: 'admin/dashboard#index'
      ActiveAdmin.routes(self)
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user || User.new

    if @user.is_admin?
      can :manage, :all
    elsif @user.persisted?
      can %i(create read update destroy), Device, user_id: @user.id
      can %i(read update), User, id: @user.id
    end
  end
end

app/models/aggregate.rb
class Aggregate < ApplicationRecord
  belongs_to :device
  validates :date, :device_id, :energy, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :devices

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :aggregates
  has_and_belongs_to_many :time_gaps
  validates :user_id, :bt_mac_address, :category, :name, :power, presence: true
end

app/models/time_gap.rb
class TimeGap < ApplicationRecord
  has_and_belongs_to_many :devices
  validates :start, :end, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable

  has_many :devices

  ROLES = %w(client admin).freeze

  validates :name, :email, :password, :password_confirmation, presence: true

  validates :role, inclusion: ROLES

  ROLES.each do |r|
    define_method "is_#{r}?" do
      role == r
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.is_admin?
      flash[:alert] = 'You are not authorized to access this resource!'
      redirect_to root_path
    end
 end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  def new
    @device = Device.new
  end

  def create
    @device = current_user.devices.build(device_params)
    respond_to do |format|
      if @device.save
        format.html { redirect_to current_user }
        format.json { head :ok }
      else
        format.html { redirect_to current_user }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |f|
      f.html
      f.json { render json: @device }
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to current_user }
        format.json { head :ok }
      else
        format.html { redirect_to current_user }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :ok }
    end
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:user_id, :bt_mac_address, :category_id, :name, :power, :validity, :active)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(_resource)
    current_user.is_client? ? root_path : admin_dashboard_path
  end

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  private

  def after_sign_in_path_for(_resource)
    current_user.is_client? ? current_user : admin_dashboard_path
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    respond_to do |f|
      f.html
      f.json { render json: @user.to_json(include: :devices) }
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = current_user || User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

 <%= render 'partials/device_form' %>

<%= link_to 'Show', device_path(@device) %>

app/views/devices/show.html.erb
<strong> BT MAC name: </strong>
<%= @device.bt_mac_address %>
<br>
<strong> Device category: </strong>
<%= @device.category.name %>
<br>
<strong> Device name: </strong>
<%= @device.name %>
<br>
<strong> Device power: </strong>
<%= @device.power %>
<br>
<strong> Device validity: </strong>
<%= @device.validity %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartHouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header navbar-brand">
         <%= link_to "Smart House", root_path %>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to "Edit user", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_device_form.html.erb
<%= simple_form_for([@user, @device]) do |f| %>
  <%= f.input :bt_mac_address, required: true, autofocus: true, label: false, placeholder: 'BT MAC Address' %>
  <%= f.input :category_id, as: :select, label: false, collection: Category.all.map { |u| [u.name, u.id] } %>
  <%= f.input :name, required: true, autofocus: true, label: false, placeholder: 'Name' %>
  <%= f.input :power, required: true, autofocus: true, label: false, placeholder: 'Power' %>
  <%= f.input :validity, autofocus: true %>
  <%= f.input :active, autofocus: true %>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site/index.html.erb
<% if user_signed_in? %>
  <h1><%= "Hello, #{current_user.name}" %></h1>
  <% if current_user.is_admin? %>
    <h3><%= link_to "Admin Dashboard", admin_dashboard_path %></h3>
  <% else %>
    <h3><%= link_to 'Your profile', current_user %></h3>
  <% end %>
<% else %>
  <h1> Please, sign in to track your devices <h1>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true, autofocus: true, label: false, placeholder: 'Name' %>
    <%= f.input :email, required: true, autofocus: true, label: false, placeholder: 'Email' %>
    <%= f.input :password, required: true, autofocus: true, label: false, placeholder: 'Password' %>
    <%= f.input :password_confirmation, required: true, autofocus: true, label: false, placeholder: 'Password confirmation' %>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to "Home", root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<h3> Devices </h3>
<table>
  <tr>
  <td>
    <strong>Device MAC Address</strong>
  </td>
  <td>
    <strong>Device category</strong>
  </td>
  <td>
    <strong>Device name</strong>
  </td>
  <td>
    <strong>Device power</strong>
  </td>
  <td>
    <strong>Device validity</strong>
  </td>
  <td>
    <strong>Device active</strong>
  </td>
  </tr>
<% @user.devices.each do |device| %>
  <tr>
    <td>
      <%= link_to "#{device.bt_mac_address}", device %>
    </td>
    <td>
      <%= device.category.name %>
    </td>
    <td>
      <%= device.name %>
    </td>
    <td>
      <%= device.power %>
    </td>
    <td>
      <%= device.validity %>
    </td>
    <td>
      <%= device.active %>
    </td>
    <td>
      <%= link_to "Edit", edit_device_path(device.id) %>
    </td>
    <td>
      <%= link_to "Delete", device, method: :delete %>
    </td>
  </tr>
<% end %>
</table>
<br>
<h3> Add new device </h3>
<%= simple_form_for Device.new do |f| %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
  <%= f.input :bt_mac_address, required: true, autofocus: true, label: false, placeholder: 'BT MAC Address' %>
  <%= f.input :category_id, as: :select, label: false, collection: Category.all.map { |u| [u.name, u.id] } %>
  <%= f.input :name, required: true, autofocus: true, label: false, placeholder: 'Name' %>
  <%= f.input :power, required: true, autofocus: true, label: false, placeholder: 'Power' %>
  <%= f.input :validity, autofocus: true %>
  <%= f.input :active, autofocus: true %>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>
<br>
<%= link_to "Edit user", edit_user_path(@user.id) %>